//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_message
    {
        public int id_category_massage { get; set; }
        public Nullable<int> id_massager { get; set; }
        public string Classic { get; set; }
        public string VR { get; set; }
        public string total_immerian { get; set; }
    }
}
