//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Client
    {
        public int ID_DetailClient { get; set; }
        public string city_client { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<int> Id_client { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
