//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Massager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Massager()
        {
            this.Detail_Massager = new HashSet<Detail_Massager>();
            this.Session = new HashSet<Session>();
        }
    
        public int Id_masseger { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string job_title { get; set; }
        public Nullable<decimal> number_of_sessions_per_day { get; set; }
        public Nullable<decimal> number_of_sessions_per_month { get; set; }
        public Nullable<int> types_of_massage { get; set; }
        public Nullable<int> id_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Massager> Detail_Massager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
        public virtual Massager Massager1 { get; set; }
        public virtual Massager Massager2 { get; set; }
    }
}
