//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ID_service { get; set; }
        public string service_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public byte[] duration { get; set; }
        public string salon_address { get; set; }
        public Nullable<int> Category_message { get; set; }
    }
}
