//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id_session { get; set; }
        public Nullable<System.DateTime> session_time { get; set; }
        public Nullable<int> ID_masseger { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> Category_message { get; set; }
        public string type_of_massage { get; set; }
        public string payment_method { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Massager Massager { get; set; }
    }
}
