//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id_user { get; set; }
        public string email { get; set; }
        public string password_hash { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string full_name { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string phone_number { get; set; }
    }
}
